### ISSUE TITLE
Multiple Requests sent for SVG sprite in Firefox

### ISSUE THREAD

**Issue by uchihamalolan** [svgmoji/svgmoji#16]
### Summary

SVG sprite rendering blinking on multiple reloads of the page in Firefox

### Steps to reproduce

- A App Requesting for the same SVG sprite 10 times (each with different `#ids`)
- Now try to access that app in Firefox

### Expected results

- Only one request for the SVG Sprite should be sent

### Actual results

- Request for SVG Sprite is sent 10 times

### Additional context

- CodePen Link: https://codepen.io/uchihamalolan/full/JjWwVYE
- In chrome, there'll be only one request sent
- In Firefox, 10 requests are sent

### Possible Solution

It seems to be a Bug in Firefox itself, links here:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1027106
- https://bugzilla.mozilla.org/show_bug.cgi?id=1678956

> _They suggested a workaround, until the issue is fixed on their side. Please go through the bug report for the workaround_

**Comment by niclashoyer** [comment]
Please note that the workarounds don't really work as using `<svg><use xlink:href="sprite.svg#foo"/></svg>` does not allow cross origin requests (which is always the case when using cdn). 😥
